# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Do something

on:
  workflow_dispatch:
    inputs:
      TOKEN:
        description: GitHub app token.
        required: true
        type: string
      repo:
        description: Remote repository.
        required: true
        type: string
      owner:
        description: Owner of remote repository
        required: true
        type: string
      ref:
        description: Ref of remote repository
        required: true
        type: string
      environment:
        description: Name of the environment to deploy.
        default: production
      environment_url:
        description: URL to view the deployment.
        required: true

jobs:
  do_something:
    name: Do something

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Vercel
        uses: actions/checkout@v3
        working-directory: /tmp

      - name: Create in_progress deployment
        id: create_deployment
        uses: '/tmp/.github/actions/create-deployment'
        working-directory: /tmp
        with:
          TOKEN: ${{ inputs.TOKEN }}
          repo: ${{ inputs.repo }}
          owner: ${{ inputs.owner }}
          ref: ${{ inputs.ref }}
          environment: ${{ inputs.environment }}
          environment_url: ${{ inputs.environment_url }}
          status: in_progress

      - name: Create success deployment
        uses: '/tmp/.github/actions/create-deployment'
        working-directory: /tmp
        with:
          TOKEN: ${{ inputs.TOKEN }}
          repo: ${{ inputs.repo }}
          owner: ${{ inputs.owner }}
          ref: ${{ inputs.ref }}
          environment: ${{ inputs.environment }}
          environment_url: ${{ inputs.environment_url }}
          status: success

      - name: Create failure deployment
        if: ${{ failure() }}
        uses: '/tmp/.github/actions/create-deployment'
        working-directory: /tmp
        with:
          TOKEN: ${{ inputs.TOKEN }}
          repo: ${{ inputs.repo }}
          owner: ${{ inputs.owner }}
          ref: ${{ inputs.ref }}
          environment: ${{ inputs.environment }}
          environment_url: ${{ inputs.environment_url }}
          status: failure
