# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Do something

on:
  workflow_dispatch:
    inputs:
      TOKEN:
        description: GitHub app token.
        required: true
        type: string
      repo:
        description: Remote repository.
        required: true
        type: string
      owner:
        description: Owner of remote repository
        required: true
        type: string

jobs:
  do_something:
    name: Do something

    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.owner }}/${{ inputs.repo }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create in-progress deployment
        id: create_deployment
        uses: ./.github/actions/create-deployment
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          environment: preview
          name: ${{ inputs.owner }}/${{ inputs.repo }}
          url: https://github.com
          status: success
